In [123]:
import pandas as pd

In [124]:
tabla = pd.read_excel('../clase-24102025/assets/Datos_climatologicos_Santa_Fe_2019.xlsx', index_col = 0)

In [125]:
tabla

                     Irradiancia (W/m²)  Temperatura (°C)
Fecha
2019-01-01 00:00:00                   0              27.9
2019-01-01 00:10:00                   0              27.8
2019-01-01 00:20:00                   0              28.0
2019-01-01 00:30:00                   0              28.0
2019-01-01 00:40:00                   0              27.9
...                                 ...               ...
2019-12-31 23:10:00                   0              25.0
2019-12-31 23:20:00                   0              25.0
2019-12-31 23:30:00                   0              25.0
2019-12-31 23:40:00                   0              24.9
2019-12-31 23:50:00                   0              24.7

[52560 rows x 2 columns]

In [126]:
tabla['Temperatura (°C)']

Fecha
2019-01-01 00:00:00    27.9
2019-01-01 00:10:00    27.8
2019-01-01 00:20:00    28.0
2019-01-01 00:30:00    28.0
2019-01-01 00:40:00    27.9
                       ...
2019-12-31 23:10:00    25.0
2019-12-31 23:20:00    25.0
2019-12-31 23:30:00    25.0
2019-12-31 23:40:00    24.9
2019-12-31 23:50:00    24.7
Name: Temperatura (°C), Length: 52560, dtype: float64

In [127]:
tabla['Temperatura (°C)'].max()

np.float64(40.7)

In [128]:
tabla['Temperatura (°C)'].describe()

count    52560.000000
mean        20.133324
std          6.655765
min          2.200000
25%         15.300000
50%         19.700000
75%         24.800000
max         40.700000
Name: Temperatura (°C), dtype: float64

In [129]:
tabla['Temp de celda (°C)'] = tabla['Temperatura (°C)'] + 0.031 * tabla['Irradiancia (W/m²)']

In [130]:
tabla

                     Irradiancia (W/m²)  Temperatura (°C)  Temp de celda (°C)
Fecha
2019-01-01 00:00:00                   0              27.9                27.9
2019-01-01 00:10:00                   0              27.8                27.8
2019-01-01 00:20:00                   0              28.0                28.0
2019-01-01 00:30:00                   0              28.0                28.0
2019-01-01 00:40:00                   0              27.9                27.9
...                                 ...               ...                 ...
2019-12-31 23:10:00                   0              25.0                25.0
2019-12-31 23:20:00                   0              25.0                25.0
2019-12-31 23:30:00                   0              25.0                25.0
2019-12-31 23:40:00                   0              24.9                24.9
2019-12-31 23:50:00                   0              24.7                24.7

[52560 rows x 3 columns]

In [131]:
N = 12 # Cantidad de Paneles
Gstd = 1000 # W/m2
Ppico = 240 # W
kp = -0.0044 # 1/ºC
Tr = 25
eta = 0.95

In [132]:
tabla['Pot (kW)'] = N * tabla['Irradiancia (W/m²)'] / Gstd * Ppico * (1 + kp * (tabla['Temp de celda (°C)'] - Tr)) * eta * 1e-3

In [133]:
tabla

,Irradiancia (W/m²),Temperatura (°C),Temp de celda (°C),Pot (kW)
Fecha,,,,
2019-01-01 00:00:00,0,27.9,27.9,0.0
2019-01-01 00:10:00,0,27.8,27.8,0.0
2019-01-01 00:20:00,0,28.0,28.0,0.0
2019-01-01 00:30:00,0,28.0,28.0,0.0
2019-01-01 00:40:00,0,27.9,27.9,0.0
...,...,...,...,...
2019-12-31 23:10:00,0,25.0,25.0,0.0
2019-12-31 23:20:00,0,25.0,25.0,0.0
2019-12-31 23:30:00,0,25.0,25.0,0.0
2019-12-31 23:40:00,0,24.9,24.9,0.0
2019-12-31 23:50:00,0,24.7,24.7,0.0

In [134]:
enero = tabla.loc['2019-01', ['Temp de celda (°C)', 'Pot (kW)']]

In [135]:
indices_enero = enero.index

In [136]:
indices_enero

DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 00:10:00',
               '2019-01-01 00:20:00', '2019-01-01 00:30:00',
               '2019-01-01 00:40:00', '2019-01-01 00:50:00',
               '2019-01-01 01:00:00', '2019-01-01 01:10:00',
               '2019-01-01 01:20:00', '2019-01-01 01:30:00',
               ...
               '2019-01-31 22:20:00', '2019-01-31 22:30:00',
               '2019-01-31 22:40:00', '2019-01-31 22:50:00',
               '2019-01-31 23:00:00', '2019-01-31 23:10:00',
               '2019-01-31 23:20:00', '2019-01-31 23:30:00',
               '2019-01-31 23:40:00', '2019-01-31 23:50:00'],
              dtype='datetime64[ns]', name='Fecha', length=4464, freq=None)

In [137]:
p_1804 = tabla.loc['2019-04-18', 'Pot (kW)']

In [138]:
p_1804

Fecha
2019-04-18 00:00:00    0.0
2019-04-18 00:10:00    0.0
2019-04-18 00:20:00    0.0
2019-04-18 00:30:00    0.0
2019-04-18 00:40:00    0.0
                      ...
2019-04-18 23:10:00    0.0
2019-04-18 23:20:00    0.0
2019-04-18 23:30:00    0.0
2019-04-18 23:40:00    0.0
2019-04-18 23:50:00    0.0
Name: Pot (kW), Length: 144, dtype: float64

In [139]:
%matplotlib qt

In [140]:
ax = p_1804.plot()

In [141]:
ax.set_ylabel('Potencia (kW)')

Text(63.958333333333336, 0.5, 'Potencia (kW)')

In [142]:
ax.set_title('Grafico de pot. del 18-04-2019')

Text(0.5, 1.0, 'Grafico de pot. del 18-04-2019')

In [143]:
curva = ax.lines[0]

In [144]:
curva.set_linewidth(2)

In [145]:
curva.set_linestyle('--')

In [146]:
curva.set_color('g')

In [147]:
enero.plot()

In [148]:
enero.plot(y = 'Pot (kW)')

In [149]:
enero.plot(x = 'Temp de celda (°C)', y = 'Pot (kW)')

In [151]:
enero.plot.scatter(x = 'Temp de celda (°C)', y = 'Pot (kW)')

In [152]:
tabla.to_clipboard()

In [153]:
tabla.to_html('test.html')

In [154]:
tabla.to_csv('salida.csv')